import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SKILL_PRESETS, PRESET_GROUPS, composePresetText, findPresets } from '../skill-presets.js';
import { GROUP_ORDER, SKILL_PHASE, renderSkillPresetsModule } from '../scripts/build-skill-presets.mjs';

// The panel offers the vendored addyosmani/agent-skills pack as ready-to-send drafts, but the pack
// itself is never packaged (AGENTS.md). skill-presets.js is the shipped slice of it, generated by
// scripts/build-skill-presets.mjs. These tests keep that slice honest: it is regenerated from .agents/
// on every run, so a pack refresh cannot silently leave the panel advertising stale workflows.
const root = fileURLToPath(new URL('..', import.meta.url));
const read = file => readFileSync(join(root, file), 'utf8');
const generated = read('skill-presets.js');

test('the shipped module is exactly what the current pack derives', () => {
  assert.equal(generated, renderSkillPresetsModule(),
    'skill-presets.js drifted from .agents/ — run `npm run build:presets` and commit the result');
});

test('every skill and every lifecycle command becomes one preset', () => {
  const skills = readdirSync(join(root, '.agents/skills')).sort();
  const commands = readdirSync(join(root, '.agents/commands')).filter(name => name.endsWith('.md')).map(name => name.replace(/\.md$/, ''));
  assert.equal(SKILL_PRESETS.filter(preset => preset.kind === 'skill').length, skills.length);
  assert.equal(SKILL_PRESETS.filter(preset => preset.kind === 'command').length, commands.length);
  for (const name of skills) assert.ok(SKILL_PRESETS.some(preset => preset.id === `skill:${name}`), `${name} has no preset`);
  for (const name of commands) assert.ok(SKILL_PRESETS.some(preset => preset.id === `command:${name}`), `/${name} has no preset`);
  assert.equal(SKILL_PRESETS.length, skills.length + commands.length);
});

test('presets are grouped by the phase AGENTS.md lists them under', () => {
  const rows = [...read('AGENTS.md').matchAll(/^\|\s*(Discover|Define|Plan|Build|Verify|Review|Ship)\s*\|\s*([^|]+?)\s*\|/gm)]
    .map(match => [match[1], match[2].split(',').map(name => name.trim()).filter(Boolean)]);
  const table = new Map();
  for (const [phase, names] of rows) for (const name of names) table.set(name, phase);
  assert.equal(table.size, Object.keys(SKILL_PHASE).length, 'AGENTS.md and the generator phase map disagree in size');
  for (const [name, phase] of table) assert.equal(SKILL_PHASE[name], phase, `${name} is ${phase} in AGENTS.md but ${SKILL_PHASE[name]} in the generator`);
  for (const preset of SKILL_PRESETS.filter(item => item.kind === 'skill')) {
    assert.equal(preset.group, SKILL_PHASE[preset.id.slice('skill:'.length)]);
    assert.ok(PRESET_GROUPS.includes(preset.group), `${preset.group} is not a known group`);
  }
  // Commands lead the list: they are the lifecycle entry points, not a phase of their own.
  assert.equal(PRESET_GROUPS[0], 'Lifecycle');
  assert.deepEqual(SKILL_PRESETS.slice(0, 9).map(preset => preset.group), Array(9).fill('Lifecycle'));
  assert.equal(GROUP_ORDER[0], 'Lifecycle');
});

test('each preset is a complete, self-contained prompt with a place for the task', () => {
  const seen = new Set();
  for (const preset of SKILL_PRESETS) {
    for (const key of ['id', 'kind', 'label', 'group', 'summary', 'prompt', 'search']) {
      assert.ok(typeof preset[key] === 'string' && preset[key].length, `${preset.id} is missing ${key}`);
    }
    assert.ok(!seen.has(preset.id), `${preset.id} is duplicated`);
    seen.add(preset.id);
    assert.ok(preset.prompt.endsWith('My task:'), `${preset.id} must end where the user's task goes`);
    assert.ok(preset.prompt.includes(preset.kind === 'command' ? `/${preset.id.slice('command:'.length)}` : preset.id.slice('skill:'.length)), `${preset.id} does not name its workflow`);
    assert.ok(preset.prompt.length < 1000, `${preset.id} is ${preset.prompt.length} characters — too long to review in a draft`);
    assert.equal(preset.prompt.includes('undefined'), false, `${preset.id} interpolated something missing`);
    assert.equal(preset.search, preset.search.toLowerCase());
  }
});

test('search matches label, group and summary, and an empty query keeps everything', () => {
  assert.equal(findPresets('').length, SKILL_PRESETS.length);
  assert.equal(findPresets('   ').length, SKILL_PRESETS.length);
  assert.deepEqual(findPresets('security').map(preset => preset.id), ['command:review', 'skill:security-and-hardening']);
  assert.deepEqual(findPresets('hardening').map(preset => preset.id), ['skill:security-and-hardening']);
  assert.ok(findPresets('review').length >= 3);
  assert.ok(findPresets('/ship').some(preset => preset.id === 'command:ship'));
  assert.deepEqual(findPresets('zzzz-no-such-workflow'), []);
});

test('a preset appends to a draft, replaces an empty one, and refuses to overflow the limit', () => {
  const preset = SKILL_PRESETS.find(item => item.id === 'skill:spec-driven-development');
  assert.equal(composePresetText('', preset, 30000).text, preset.prompt);
  assert.equal(composePresetText('   \n ', preset, 30000).text, preset.prompt);
  const appended = composePresetText('Earlier thought', preset, 30000);
  assert.equal(appended.ok, true);
  assert.equal(appended.text, `Earlier thought\n\n${preset.prompt}`);
  // Trailing whitespace never becomes a paragraph of its own.
  assert.equal(composePresetText('Earlier thought\n\n', preset, 30000).text, appended.text);
  // Fail closed rather than truncate: the caller reports the overflow and inserts nothing.
  // 15 characters of draft plus the 2-character separator, against a limit 5 short of the prompt.
  const tight = composePresetText('Earlier thought', preset, preset.prompt.length + 5);
  assert.equal(tight.ok, false);
  assert.equal(tight.overflow, 12);
  assert.equal(composePresetText('x'.repeat(10), preset, 10).overflow, preset.prompt.length + 2);
  assert.equal(composePresetText(undefined, preset, 30000).text, preset.prompt);
});

test('the prompt library ships with the extension while the pack itself does not', () => {
  const packaged = JSON.parse(read('extension-files.json'));
  assert.ok(packaged.includes('skill-presets.js'), 'skill-presets.js must be in the release allow-list');
  assert.equal(packaged.some(file => file === 'AGENTS.md' || file.startsWith('.agents/') || file.startsWith('skills/') || file.startsWith('scripts/')), false);
  assert.match(generated, /^\/\/ GENERATED by scripts\/build-skill-presets\.mjs/, 'the shipped file must say it is generated');
  assert.match(generated, /npm run build:presets/);
  // The module is a plain ES module with no imports of its own, so nothing else has to ship with it.
  assert.doesNotMatch(generated, /\bfrom\s+'\.\//);
  assert.match(read('package.json'), /"build:presets": "node scripts\/build-skill-presets\.mjs"/);
});
